### ISSUE TITLE
Failure to build package

### ISSUE THREAD

**Issue by rrrlw** [stulacy/multistateutils#2]
R CMD build fails because package `webshot` is unavailable and not listed in the package dependencies list in `multistateutils`'s DESCRIPTION file (in Imports or Suggests). Failure happens in lines 347-349. Note that after installing `webshot`, R CMD build still fails because a relevant connection cannot be opened (screenshot below of both errors in R CMD build; second call to R CMD build was after `webshot` was installed).

![multistateutils build](https://user-images.githubusercontent.com/6846515/44130476-cf85beb4-a01b-11e8-99f6-114d4067d443.png)

Edit: issue was reproduced on Ubuntu 18 and Windows 10 machines.

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/893).

**Comment by stulacy** [comment]
I'm not sure about which of my dependencies requires `webshot` and why it isn't being installed automatically. I could add it to Imports if that would fix that first issue.

For the "Cannot open the connection" issue, I believe this is caused by being run as a script. I've removed this call from the Vignette and added a screenshot instead. Let me know if you can install it and run these lines in an interactive session.

On a side note, what is the preferred way of checking a package with Rcpp source? I generally used "Clean and rebuild" from RStudio then `devtools::check()`, which always ran successfully. I only got the connection error when manually running `R CMD build`.

**Comment by rrrlw** [comment]
Great! R CMD build now works perfectly for me, appears that the "Cannot open connection" issue is fixed. However, it seems that [CRAN check](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/multistateutils-00check.html) is also having a problem with the `webshot` dependency. I think adding it to the Imports or Suggests field is reasonable (although it would likely also be a good idea to find out where it's being used).

**Comment by rrrlw** [comment]
Since CRAN seems to use R CMD build and R CMD check, those are what I prefer. However, I would expect that running `devtools::check()` with a clean environment would have identical behavior. Unsure what's happening...

**Comment by rrrlw** [comment]
Fix for #3 solves this issue as well.
