### ISSUE TITLE
Vignette not building in development version

### ISSUE THREAD

**Issue by jenniferthompson** [stulacy/multistateutils#6]
`vignette(package = "multistateutils")` didn't show any vignettes with the development version. Happy to close if this is just an artifact of using the development version, but the CRAN index page also lists this as "Vignette Title" so something may not be building correctly?

![image](https://user-images.githubusercontent.com/7783352/46308542-894f6380-c57f-11e8-9f04-8ddde995e5c3.png)

**Comment by stulacy** [comment]
The vignette not building correctly can be fixed by setting `build_vignettes=TRUE` in the `devtools::install_github()` call; I've added this information to the `README`. 

The second issue with the vignette title not appearing was simply an oversight by me that I've also fixed in the development version. Let me know if the changes work for you!

**Comment by jenniferthompson** [comment]
Ah, sorry I didn't realize there was a `build_vignettes` argument that could be used (didn't click that far in the help files). Reinstalled and working!
